### ISSUE TITLE
Issue with 433MHz devices: Can turn on, but not off

### ISSUE THREAD

**Issue by robi782** [kmifka/hass_lmair#12]
Hi everyone,

I'm experiencing an issue with my 433MHz sockets and switches after integrating them. I can successfully turn all of them on, but I'm unable to turn them off again.

Is there a specific setting within Home Assistant that I might have missed to resolve this? Or is there something that needs to be configured in the LightManager Air to enable the "off" command?

I'm also wondering if this could be a bug that needs to be reported.

Any help or guidance on this would be greatly appreciated.

Thanks!

**Comment by kmifka** [comment]
Please share the config.xml of your Light Manager and let me know which entity and action this issue occurs with.

**Comment by robi782** [comment]
Many thanks for your work and for the check of this issue here. :)

[config.xml](https://github.com/user-attachments/files/22192402/config.xml)

**Comment by kmifka** [comment]
And which actuator doesnt work?

**Comment by robi782** [comment]
Sorry, here the power-outlets which does not work:

"Kochinsel"
"Leselampe"
"Bluetooth"

All these Actuators are wireless sockets. It can actually be stated that all 433Mhz wireless sockets can only be switched on but not off via the integration Home Assistant.

GreetZ

**Comment by robi782** [comment]
No Idea? I hope this issue can be solved. I can not use the integration with this error.

**Comment by kmifka** [comment]
Same here, enable debug logging by adding the following to your configuration.yaml:

logger:
default: info
logs:
custom_components.light_manager_air: debug

After enabling debug logging, restart Home Assistant, try to turn the mentioned entities on and off, and then send me the logs from this attempt.

Thank you for your patience and for helping improve the integration!

Best regards,
kmifka

**Comment by robi782** [comment]
Attached the log. yaml configured.

Info:
ON "Kochinsel" = OK
after that try to shut off three times = NOK

ON "Leselmape" = OK
after that try to shut off three times = NOK

EDIT:I think it's also important to mention that the status LED on the Light Manager Air lights up when the signal is "on" or "off," so something is being sent from the LMA.  My guess is that only an "on" signal is being sent at any time. As far as I can see, there's no off signal in the log either?

Thanks for view.

[home-assistant_2025-09-12T17-48-26.281Z.log](https://github.com/user-attachments/files/22303548/home-assistant_2025-09-12T17-48-26.281Z.log)


Try this one:

logger:
  default: info
  logs:
    custom_components.light_manager_air: debug
    homeassistant.core: debug

**Comment by robi782** [comment]
Hey, could you Check the Logfile?

**Comment by robi782** [comment]
@kmifka could you check the logfile?

**Comment by robi782** [comment]
@kmifka is this project closed?

**Comment by robi782** [comment]
@kmifka could you please answer?

**Comment by robi782** [comment]
@kmifka ist the project closed?

**Comment by kmifka** [comment]
Thanks for the detailed log and config.xml. I’ve pushed a fix that no longer relies on the OFF command being at index 2 and added debug logging to show the exact payload we send to the Light Manager.

What to test:
- Update the integration to the latest main (or reinstall via HACS to pull the new commit).
- Enable debug logging:
  logger:
    default: info
    logs:
      custom_components.light_manager_air: debug
- Restart HA, then try turning the affected 433 MHz sockets off and on. If it still fails, please attach the new log snippet so I can see the exact command we sent.

I’m closing this for now; if OFF still doesn’t work with the new build, please reopen with the fresh debug log.

Quick personal note: I maintain this project in my spare time and have very limited bandwidth right now. So far there’s been neither active contributions nor support via BuyMeACoffee. You once wrote “Donation follows” — instead I’ve mostly been pinged to hurry up. I understand the frustration, but please be patient; I ship when time permits. If you enjoy the integration, I’d really appreciate a financial donation — it helps keep the project alive.

**Comment by robi782** [comment]
First, to you. Sorry. I didn't mean to cause any trouble, and I didn't. My repeated inquiries were simply due to the lack of response. I thought it was over and done with.

You're right about the donation, though; I'll make that happen.

Regarding the issue: The functionality is still incorrect. The standard button (entity), for example, for "Kitchen Island," only ever sends an "ON" signal. However, this only works via the details/popup window here:

<img width="672" height="661" alt="Image" src="https://github.com/user-attachments/assets/4b821fb4-ebc3-4cac-8135-17264353fd0c" />

not via the button on the overview page.

<img width="286" height="67" alt="Image" src="https://github.com/user-attachments/assets/133e97c3-4db2-49cd-8b4d-72196856c8f0" />

When testing with Bubble Card, it also works via the popup, but it can't be switched off there. However, it can be switched off using the "Card Button." The Lightmanager then sends an "off" signal, but this isn't always reliable either. Sometimes the light goes off, sometimes it doesn't.

<img width="398" height="69" alt="Image" src="https://github.com/user-attachments/assets/a93f2db2-65cf-451e-8641-b6919ab2a472" />

Apparently, the Lightmanager isn't interacting correctly with HAOS. A switch/toggle doesn't work this way.

Thank you in advance for your support and please don't stress. ;)

---

[home-assistant_2025-11-29T09-04-16.993Z.log.zip](https://github.com/user-attachments/files/23832879/home-assistant_2025-11-29T09-04-16.993Z.log.zip)

---

2025-11-28 17:17:33.173 DEBUG (MainThread) [custom_components.light_manager_air.base_entity] Sending command for light.kochinsel (Kochinsel): name='on' index=0 payload=[('cmd', 'on,typ,it,did,21974500,aid,19,acmd,1,seq,6,smk,5,1'), ('id', '19')]

2025-11-28 17:17:54.094 DEBUG (MainThread) [custom_components.light_manager_air.base_entity] Sending command for light.kochinsel (Kochinsel): name='off' index=2 payload=[('cmd', 'off,typ,it,did,21974500,aid,19,acmd,0,seq,6,smk,5,0'), ('id', '19')]

The difference between ON and OFF seems to be primarily in the name='on' / name='off' fields and the acmd,1 / acmd,0 parameter in the payload. The integration seems to generate the correct payload, but the standard HA UI fails to trigger the correct service call.

**Comment by robi782** [comment]
I configured it like this and then it works; the off and on buttons are separated here:

`type: entities
title: Lightmanager Fix Test (Explizit)
entities:
  - entity: light.kochinsel
    name: Schalten (Standard-Toggle)
  - type: call-service
    name: ➡️ Explizit AN
    icon: mdi:lightbulb-on
    action_name: AN
    service: light.turn_on
    service_data:
      entity_id: light.kochinsel
  - type: call-service
    name: ➡️ Explizit AUS
    icon: mdi:lightbulb-off
    action_name: AUS
    service: light.turn_off
    service_data:
      entity_id: light.kochinsel
`

But then it doesn't look so nice:

<img width="496" height="270" alt="Image" src="https://github.com/user-attachments/assets/69e6d8d1-e568-45c2-ac16-0bfc115155e1" />

**Comment by robi782** [comment]
@kmifka please reopen, i have no permission to do that.
